- name: app setup
  import_role:
    name: common
    tasks_from: app_setup

- name: install java
  import_role:
    name: common
    tasks_from: java
- name: service file copy and daemon reload
  import_role:
    name: common
    tasks_from: systemd_setup

- name: install mysql client library
  ansible.builtin.package:
    name: mysql
    state: present
- name: install python dependencies
  pip:
    name: PyMySQL
    executable: pip3.9
- name: Import the dump file into the MySQL database
  community.mysql.mysql_db:
    name: all
    state: import
    target: "{{ item }}"
    login_user: "root"
    login_password: "RoboShop@1"
    login_host: "{{ MYSQL_HOST }}"
  loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql
- name: load the daemon services
  ansible.builtin.systemd_service:
    name: shipping 
    daemon_reload: true
    state: restarted
    enabled: true