[frontend]
172.31.40.228

[local]
127.0.0.1

[mongodb]
localhost

[redis]
localhost
[mysql]
localhost
[rabbitmq]
localhost
[catalogue]
localhost
[user]
localhost
[cart]
localhost
[payment]
localhost
[dispatch]
localhost
# [frontend:vars]
# my_name=inventory
# my-age=10
# my-city=hyderabad
