- name: app_setup
  import_role:
    name: common
    tasks_from: app_setup

- name: python and dependecy installation
  import_role:
    name: common
    tasks_from: python

- name: service copy and daemon reload
  import_role:
    name: common
    tasks_from: systemd_setup
  
- name: service restart
  import_role:
    name: common
    tasks_from: restart