- name: Lookup secretsmanager secret in the current region
  ansible.builtin.debug: msg="{{ lookup('amazon.aws.aws_ssm', '/roboshop/dev/MYSQL_ROOT_PASSWORD', region='us-east-1',decrypt=False)}}" 

- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present
- name: start the mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true
- name: set mysql password
  command: mysql_secure_installation --set-root-pass "{{ mysql_root_p }}"
  register: result
  failed_when: "result.rc != 0 and 'already secured' not in result.stderr"
  changed_when: result.rc == 0
- name: pring result
  ansible.builtin.debug:
    var: result
