# mysql_root_pass: RoboShop@1
#mysql_root_p: "{{ lookup('amazon.aws.aws_secret', 'dev/roboshop/mysqlpass', region='us-east-1')}}"
mysql_root_p: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/dev/MYSQL_ROOT_PASSWORD', region='us-east-1',decrypt=False)}}"