- name: app setup
  import_role:
    name: common
    tasks_from: app_setup
- name: nodejs app_setup
  import_role:
    name: common
    tasks_from: nodejs
- name: service and daemon 
  import_role:
    name: common
    tasks_from: systemd_setup
- name: service re start
  import_role:
    name: common
    tasks_from: restart